module Sorcerer
  VERSION_MAJOR = 0
  VERSION_MINOR = 0
  VERSION_BUILD = 5
  VERSION_BETA  = 1
  if VERSION_BETA == 0
    VERSION_NUMBERS = [VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD]
  else
    VERSION_NUMBERS = [VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD, VERSION_BETA]
  end
  VERSION = VERSION_NUMBERS.join(".")
end
